project:
  type: book
  output-dir: docs

book:
  title: "template"
  author: "AI Whoo School"

  chapters:
    - index.qmd
    - part: "Chapter 3: Python and Pandas"
      chapters:
      - Chapter3/Chapter3-Part1.qmd
      - Chapter3/Chapter3-Part2.qmd
      - Chapter3/Chapter3-Part3.qmd
      - Chapter3/Chapter3-Part4.qmd
    - part: "Chapter 4: ETL in Action"
      chapters:
      - Chapter4/Chapter4-Part1.qmd
      - Chapter4/Chapter4-Part2.qmd
      - Chapter4/Chapter4-Part3.qmd
      - Chapter4/Chapter4-Part4.qmd
      - Chapter4/Chapter4-Part5.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
