project:
  type: website
  output-dir: docs

website:
  title: "template"

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Project Title

      - href: Chapter3/Chapter3-Part1.qmd
        text: Chapter 3 - Python and Pandas (Part 1)

      - href: Chapter3/Chapter3-Part2.qmd
        text: Chapter 3 - Python and Pandas (Part 2)

      - href: Chapter3/Chapter3-Part3.qmd
        text: Chapter 3 - Python and Pandas (Part 3)

      - href: Chapter3/Chapter3-Part4.qmd
        text: Chapter 3 - Python and Pandas (Part 4)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
